//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverRegister
    {
        public System.Guid DriverId { get; set; }
        public string DriverName { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public System.Guid Creator { get; set; }
        public string DriverCardNo { get; set; }
        public Nullable<bool> Active { get; set; }
        public System.Guid OwnerId { get; set; }
        public string VehicleNumber { get; set; }
    }
}
