//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLineModel
    {
        public string PONumber { get; set; }
        public string POLine { get; set; }
        public string ProviderCode { get; set; }
        public string ProviderName { get; set; }
        public string CompanyCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> OverTolerance { get; set; }
        public Nullable<decimal> UnderTolerance { get; set; }
        public Nullable<bool> isUnlimited { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<bool> isRelease { get; set; }
        public Nullable<bool> isDeliveryCompleted { get; set; }
        public Nullable<decimal> SoLuongDaNhap { get; set; }
        public Nullable<bool> isPMCCompleted { get; set; }
        public string WarehouseCode { get; set; }
    }
}
