//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class POMasterModel
    {
        public string PONumber { get; set; }
        public string ProviderCode { get; set; }
        public string ProviderName { get; set; }
        public Nullable<decimal> QtyTotal { get; set; }
        public Nullable<bool> isNhapKhau { get; set; }
        public Nullable<bool> isCompelete { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> SoLuongDaNhap { get; set; }
    }
}
