//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserModel
    {
        public System.Guid userid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<System.Guid> memberof { get; set; }
        public Nullable<bool> active { get; set; }
        public string token { get; set; }
        public Nullable<int> rolecode { get; set; }
        public string UserType { get; set; }
        public string taxcode { get; set; }
        public Nullable<bool> IsService { get; set; }
        public Nullable<bool> IsVeTinh { get; set; }
    }
}
