//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleRegisterPODetailModel
    {
        public System.Guid VehicleRegisterPODetailId { get; set; }
        public Nullable<System.Guid> VehicleRegisterMobileId { get; set; }
        public string PONumber { get; set; }
        public string POLine { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> TiLe { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> TrongLuong { get; set; }
    }
}
