//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleRegisterMobileModel
    {
        public System.Guid VehicleRegisterMobileId { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public Nullable<System.DateTime> ThoiGianToiDuKien { get; set; }
        public Nullable<System.DateTime> ThoiGianToiThucTe { get; set; }
        public string DVVC { get; set; }
        public string SoDonHang { get; set; }
        public string GiaoNhan { get; set; }
        public string VehicleNumber { get; set; }
        public string DriverName { get; set; }
        public string DriverIdCard { get; set; }
        public Nullable<decimal> TrongLuongGiaoDuKien { get; set; }
        public Nullable<decimal> TrongLuongGiaoThucTe { get; set; }
        public Nullable<int> CungDuongCode { get; set; }
        public string CungDuongName { get; set; }
        public string Assets { get; set; }
        public string Note { get; set; }
        public Nullable<bool> AllowEdit { get; set; }
        public string DVVCCode { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<decimal> TapChat { get; set; }
        public string ScaleTicketCode { get; set; }
        public Nullable<System.Guid> UserRegisterId { get; set; }
        public Nullable<System.Guid> UserActiveId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
